### ISSUE TITLE
Running wpg with Raspbian Jessie light and i3

### ISSUE THREAD

**Issue by geoawesome** [deviantfero/wpgtk#123]
get this error after running wpg 
(sorry if its a stupid fix, I am quite new to this)

> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/sample.py", line 7, in <module>
>     import Image
> ImportError: No module named 'Image'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/wpg", line 7, in <module>
>     from wpgtk.__main__ import main
>   File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/__main__.py", line 10, in <module>
>     from .data import themer
>   File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/themer.py", line 9, in <module>
>     from . import color
>   File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/color.py", line 13, in <module>
>     from . import sample
>   File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/sample.py", line 9, in <module>
>     from PIL import Image
>   File "/home/pi/.local/lib/python3.5/site-packages/PIL/Image.py", line 64, in <module>
>     from . import _imaging as core
> ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

**Comment by geoawesome** [comment]
unfortunately even after these commands the same error shows up

> sudo apt-get install feh python-gobject python-imaging python-dev python-setuptools libjpeg-dev xsltproc python3-dev python3-pip -y
> sudo apt-get install python3-pillow -y
> sudo pip3 install wpgtk
> sudo pip3 install pillow
> sudo pip3 install pywal

_Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/sample.py", line 7, in <module>
    import Image
ImportError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 7, in <module>
    from wpgtk.__main__ import main
  File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/__main__.py", line 10, in <module>
    from .data import themer
  File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/themer.py", line 9, in <module>
    from . import color
  File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/color.py", line 13, in <module>
    from . import sample
  File "/home/pi/.local/lib/python3.5/site-packages/wpgtk/data/sample.py", line 9, in <module>
    from PIL import Image
  File "/home/pi/.local/lib/python3.5/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory_

**Comment by deviantfero** [comment]
try this: sudo apt-get install libopenjp2-7

**Comment by geoawesome** [comment]
YES, thank you so much @deviantfero  your a legend, after installing libopenjp2-7 

> (sudo apt-get install libopenjp2-7)

 i came into another error with :
```
Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/wpgtk/__main__.py", line 281, in main
    _gui = __import__("wpgtk.gui.theme_picker", fromlist=['theme_picker'])
  File "/usr/local/lib/python3.5/dist-packages/wpgtk/gui/theme_picker.py", line 4, in <module>
    from . import color_grid
  File "/usr/local/lib/python3.5/dist-packages/wpgtk/gui/color_grid.py", line 11, in <module>
    from .color_picker import ColorDialog
  File "/usr/local/lib/python3.5/dist-packages/wpgtk/gui/color_picker.py", line 3, in <module>
    require_version("Gtk", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
So did some research and found I needed the gtk dependency's, so after `sudo apt install gir1.2-gtk-3.0` it work flawlessly :D

For anyone that is interested my full install to get wpgtk to work was:
```
sudo apt-get install feh python-gobject python-imaging python-dev python-setuptools libjpeg-dev xsltproc python3-dev python3-pip libopenjp2-7 gir1.2-gtk-3.0 python3-pillow -y
sudo pip3 install wpgtk
sudo pip3 install pillow
sudo pip3 install pywal
```
