### ISSUE TITLE
Unable to "Set" Wallpaper (6.0.6)

### ISSUE THREAD

**Issue by ejmiller8** [deviantfero/wpgtk#151]
Attempting to set a wallpaper with wpgtk results in (I have attempted to do this with "Use VTE Fix" toggled on and off):

[i] theme_picker  current wallpaper: .current
[i] image         Using image WaterRockSky.jpg.
[i] theme         Set theme to _home_ej__config_wpg_wallpapers_WaterRockSky_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image WaterRockSky.jpg.
[i] theme         Set theme to _home_ej__config_wpg_wallpapers_WaterRockSky_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/wpgtk/gui/theme_picker.py", line 142, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.7/site-packages/wpgtk/data/themer.py", line 38, in set_theme
    pywal.sequences.send(colors, WPG_DIR, vte_fix=use_vte)
TypeError: send() got an unexpected keyword argument 'vte_fix'

**Comment by deviantfero** [comment]
could you tell me what `pywal` version are you running? it should be `3.3.0`

**Comment by ejmiller8** [comment]
wal -v       
wal 3.3.0

I removed and reinstalled the default templates I had with wpg-install.sh also.

**Comment by deviantfero** [comment]
I think it's possible you have 2 `wal` executables in your computer, could you post the output of

`which wal` and `whereis wal` ?

**Comment by ejmiller8** [comment]
which wal
/usr/bin/wal

whereis wal
wal: /usr/bin/wal

**Comment by deviantfero** [comment]
Please try to uninstall `wal` with your package manager and with `pip` afterwards, I'm suspecting this because the stacktrace seems to indicate there's no `vte_fix` argument in `pywal.sequences.send`, but `pywal` has this function clearly defined here

https://github.com/dylanaraps/pywal/blob/master/pywal/sequences.py#L72

sorry to make you go through this hoops, but I need to be sure it's some other kind of issue

**Comment by ejmiller8** [comment]
I uninstalled and reinstalled pywal via pip and am still getting the same vtw_fix error:

[i] theme_picker  current wallpaper: .current
[i] image         Using image WaterRockSky.jpg.
[i] theme         Set theme to _home_ej__config_wpg_wallpapers_WaterRockSky_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image WaterRockSky.jpg.
[i] theme         Set theme to _home_ej__config_wpg_wallpapers_WaterRockSky_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/wpgtk/gui/theme_picker.py", line 142, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.7/site-packages/wpgtk/data/themer.py", line 38, in set_theme
    pywal.sequences.send(colors, WPG_DIR, vte_fix=use_vte)
TypeError: send() got an unexpected keyword argument 'vte_fix'

**Comment by deviantfero** [comment]
could you do the following:
```
$ python3
>> import pywal
>> help(pywal.sequences.send)
```

post results please

**Comment by ejmiller8** [comment]
Help on function send in module pywal.sequences:

send(colors, cache_dir='/home/ej/.cache/wal', to_send=True)
    Send colors to all open terminals.

**Comment by deviantfero** [comment]
yeah, there seems to be a discrepancy between the version you have installed and the version that actually  gets imported, what distribution are you using?

this is what I get:
```
send(colors, cache_dir='/home/fernando/.cache/wal', to_send=True, vte_fix=False)
```

**Comment by ejmiller8** [comment]
I'm using 5.1.3-arch1-1-ARCH

**Comment by deviantfero** [comment]
how did you install pywal and wpgtk initially? I would recommend try uninstalling from your package manager both packages then try to remove them from `pip` and finally, simply re-install `wpgtk-git` from the aur.

now, when you do this, what do you get?
```
>>> import pywal
>>> pywal.__version__
'3.3.0'
```

**Comment by ntk148v** [comment]
I've faced the same issue (same version as well, ubuntu 18.04).

**Comment by deviantfero** [comment]
I'm closing this for inactivity, hope it worked out for you, please don't doubt to open a new issue or re-open this one if you're still having issues
