### ISSUE TITLE
Error since updating system

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#169]
Error since the full pacman -Syu applied last night below.  Using the AUR wpgtk-git package.

[kleshas@arch ~]$ wpg
Traceback (most recent call last):
  File "/usr/bin/wpg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wpgtk==6.0.11' distribution was not found and is required by the application

**Comment by Batresh** [comment]
Had the exactly same errors after system upgrade. 
I fixed it by installing wpgtk-git again with my aur package manager

**Comment by kleshas** [comment]
I knew this was an option, and I've done it many times before with other packages.  Sorry about the waste of time, and thanks for the reminder - works fine now.  :)
