### ISSUE TITLE
Issues with Pillow

### ISSUE THREAD

**Issue by nosteppysnek1776** [deviantfero/wpgtk#173]
Bear in mind as you read this that I am basically technologically illiterate. I am using wpgtk on a system running Manjaro, built from the AUR package. Today I started getting this unexpectedly:

Traceback (most recent call last):
  File "/usr/bin/wpg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow>=4.2.1' distribution was not found and is required by wpgtk

I have Pillow-SIMD installed on my system, I believe SIMD specifically is a requirement of something else I use, but I am unsure. If I recall correctly, this was a problem that I had in the past and solved previously by editing the requirements file, but all attempts to do that today have not yielded results. Additionally, the AUR package doesn't appear to have been updated in approximately a year, so I'm unsure how or why a reversion would occur. Please let me know if you have any ideas, and thank you for the work you do.

**Comment by deviantfero** [comment]
have you tried re-installing python-pillow?

**Comment by nosteppysnek1776** [comment]
I was using Manjaro's package manager, which had installed pillow but I don't understand enough to explain why that wasn't sufficient. I just installed it with pip and it works. Thanks for the help.
