### ISSUE TITLE
wpg failed after reboot

### ISSUE THREAD

**Issue by Ahira-hub** [deviantfero/wpgtk#194]
Hello,
I'm running Kubuntu 20.04, BSPWM. 
On first install, wpg ran just fine and set the wallpaper. Terminal changed color as well. However, none of the apps like dolphin, firefox, settings etc changed. So I changed  /etc/environment to QT_QPA_PLATFORMTHEME=gtk2
After this change and reboot, wpg won't launch. I get a traceback:

❯ wpg
[i] theme_picker  current wallpaper: animesky.png
Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wpgtk/__main__.py", line 314, in main
    _gui.run(args)
  File "/usr/local/lib/python3.8/dist-packages/wpgtk/gui/theme_picker.py", line 193, in run
    win = mainWindow(args)
  File "/usr/local/lib/python3.8/dist-packages/wpgtk/gui/theme_picker.py", line 45, in __init__
    self.fpage = template_grid.TemplateGrid(self)
  File "/usr/local/lib/python3.8/dist-packages/wpgtk/gui/template_grid.py", line 63, in __init__
    pixbuf = Gtk.IconTheme.get_default().load_icon(icon, 64, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'document-open' not present in theme hicolor (0)

**Comment by deviantfero** [comment]
it seems that your theme is missing a specific icon, could you try setting a different gtk2 theme?

**Comment by Ahira-hub** [comment]
Yep that was it. Thank you! I'm running into a different issue now where sequences are not being updated. So every time I open a new terminal, it's using old colors.

**Comment by Ahira-hub** [comment]
Got it all figured out. Was using the wrong sequences. Thank you for the assist and the wonderful app!
