### ISSUE TITLE
GUI Fails to Launch

### ISSUE THREAD

**Issue by Thomashighbaugh** [deviantfero/wpgtk#205]
I get the following when entering `wpg` in my terminal, the `.desktop` also doesn't launch 

```bash
[i] theme_picker  current wallpaper: .current
Traceback (most recent call last):
  File "/home/[redacted]/.local/bin/wpg", line 8, in <module>
    sys.exit(main())
  File "/home/[redacted]/.local/lib/python3.8/site-packages/wpgtk/__main__.py", line 316, in main
    _gui.run(args)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/wpgtk/gui/theme_picker.py", line 193, in run
    win = mainWindow(args)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/wpgtk/gui/theme_picker.py", line 46, in __init__
    self.optpage = option_grid.OptionsGrid(self)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/wpgtk/gui/option_grid.py", line 143, in __init__
    self.load_opt_list()
  File "/home/[redacted]/.local/lib/python3.8/site-packages/wpgtk/gui/option_grid.py", line 215, in load_opt_list
    .set_active(settings.getboolean("auto_adjust", False))
  File "/usr/lib/python3.8/configparser.py", line 1303, in get
    return _impl(self._name, option, raw=raw, vars=vars,
  File "/usr/lib/python3.8/configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.8/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.8/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.8/configparser.py", line 1163, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: truee
```

**Comment by deviantfero** [comment]
could you share ".config/wpg/wpg.conf"? seems like you have a bogus config
file, it says "truee" instead of "true"

    -- Fernando Vásquez

**Comment by Thomashighbaugh** [comment]
You were on the money, there wasn't a directory in my ~/.config directory, so I mkdir'ed one and threw in one of the default wpg.conf files included in the package and it is all working fantastic! Thanks a million!

**Comment by deviantfero** [comment]
cool!
