### ISSUE TITLE
Cannot launch the GUI

### ISSUE THREAD

**Issue by chrisJuresh** [deviantfero/wpgtk#225]
I cannot open the program in dmenu and this is the output when typing wpg in the terminal. What am I missing?
```
[chris@desktop ~]$ wpg

Traceback (most recent call last):
  File "/usr/bin/wpg", line 33, in <module>
    sys.exit(load_entry_point('wpgtk==6.2.3', 'console_scripts', 'wpg')())
  File "/usr/lib/python3.9/site-packages/wpgtk/__main__.py", line 315, in main
    _gui = __import__("wpgtk.gui.theme_picker", fromlist=['theme_picker'])
  File "/usr/lib/python3.9/site-packages/wpgtk/gui/theme_picker.py", line 4, in <module>
    from . import color_grid
  File "/usr/lib/python3.9/site-packages/wpgtk/gui/color_grid.py", line 12, in <module>
    from .color_picker import ColorDialog
  File "/usr/lib/python3.9/site-packages/wpgtk/gui/color_picker.py", line 2, in <module>
    from gi import require_version
ImportError: cannot import name 'require_version' from 'gi' (unknown location)
```

**Comment by chrisJuresh** [comment]
Nevermind had to install python-gobject manually.
