### ISSUE TITLE
WPGTK distribution not found

### ISSUE THREAD

**Issue by ian-mitchell-001** [deviantfero/wpgtk#226]
I tried to set a wallpaper using `wpg`, and I ended up getting
```
Traceback (most recent call last):
  File "/usr/bin/wpg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wpgtk==6.0.12' distribution was not found and is required by the application
```

I have `wpgtk-git` installed from the AUR, so perhaps it's something to do with the latest build's makefile?

**Comment by deviantfero** [comment]
huh, weird, that's how I've got it installed in my system too, via AUR, have you tried removing and re-installing? your settings and wallpapers should stay in place

**Comment by ian-mitchell-001** [comment]
That seemed to work. Idk what was up with my computer, but that should have fixed it no problem.
