### ISSUE TITLE
error when trying to pip3 install wpgtk

### ISSUE THREAD

**Issue by shaunverpoort** [deviantfero/wpgtk#227]
Hi,
Sorry if there is any misunderstanding, I am still new to Linux and the terminal.

Linux mint 20.1 
pip3 version is: 3.8

When I try to _sudo pip3 install wpgtk_, I get the following error:

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7uqkeyxo/wpgtk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7uqkeyxo/wpgtk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7uqkeyxo/wpgtk/pip-egg-info
         cwd: /tmp/pip-install-7uqkeyxo/wpgtk/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7uqkeyxo/wpgtk/setup.py", line 10, in <module>
        import wpgtk
      File "/tmp/pip-install-7uqkeyxo/wpgtk/wpgtk/__init__.py", line 4, in <module>
        from .data.config import __version__
      File "/tmp/pip-install-7uqkeyxo/wpgtk/wpgtk/data/__init__.py", line 1, in <module>
        from . import color
      File "/tmp/pip-install-7uqkeyxo/wpgtk/wpgtk/data/color.py", line 3, in <module>
        import pywal
    ModuleNotFoundError: No module named 'pywal'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by shaunverpoort** [comment]
fixed after installing pywall..

my bad, like I said I'm new to all this haha, closing.
