### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#245]
Was tweaking the wpg setup last night.  Everything was working great, had a few templates, and was working on a new conky one.  Started getting the error below when running wpg -m at the command line.  wpg changes colours, the terminal changes, but the wallpaper does not.  Other issues with KeyError in Issues here imply a problem with a template, so I've removed all templates, reinstalled wpgtk-git from scratch.  Same error, even with the current situation of the templates folder being empty.

`wpg -m
[i] image         Using image wallhaven-x18w1v_2560x1440.png.
[i] theme         Set theme to _home_kleshas__config_wpg_wallpapers_wallhaven-x18w1v_2560x1440_png_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
Traceback (most recent call last):
  File "/usr/bin/wpg", line 33, in <module>
    sys.exit(load_entry_point('wpgtk==6.5.3', 'console_scripts', 'wpg')())
  File "/usr/lib/python3.9/site-packages/wpgtk/__main__.py", line 305, in main
    process_args(args)
  File "/usr/lib/python3.9/site-packages/wpgtk/__main__.py", line 181, in process_args
    themer.set_theme(filename, filename, args.r)
  File "/usr/lib/python3.9/site-packages/wpgtk/data/themer.py", line 41, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/usr/lib/python3.9/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.9/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
KeyError: "\n\nfont = 'Liberation Mono Regular"`

arch linux, swaywm.  wpg --version: 6.5.3

**Comment by kleshas** [comment]
Fixed.  It was a template in wal.
