### ISSUE TITLE
Failed to set template at i3

### ISSUE THREAD

**Issue by lucasreis1** [deviantfero/wpgtk#260]
I'm manually adding a template from file `~/.i3/config` using the GUI and following the base file provided by [your template repository](https://github.com/marzzzello/dotfiles/blob/master/.config/wpg/templates/i3.base) but whenever I try to change the theme I get the following error:

```
[lucasr@lucas ~]$ wpg
[i] theme_picker  current wallpaper: arseniy_park_day.jpg
[i] image         Using image arseniy_park_day.jpg.
[i] theme         Set theme to _home_lucasr__config_wpg_wallpapers_arseniy_park_day_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] files         created backup /home/lucasr/.i3/config.bak
[i] files         added lucasr_i3_config.base @ /home/lucasr/.i3/config
[i] image         Using image arseniy_park_day.jpg.
[i] theme         Set theme to _home_lucasr__config_wpg_wallpapers_arseniy_park_day_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[i] color         wrote: icon-step1
[i] color         wrote: gtk3.0
[i] color         wrote: config_alacritty_alacritty.yml
[i] color         wrote: gtk3.20
Exception in thread Thread-5 (change_colors):
Traceback (most recent call last):
[i] color         wrote: gtk2
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lucasr/.local/lib/python3.10/site-packages/wpgtk/data/color.py", line 100, in change_colors
    tmp_data = tmp_data.format_map(colors)
ValueError: Format string contains positional fields
[w] reload        No settings daemon found, just refreshing Adwaita theme from gsettings
[i] wallpaper     Set the new wallpaper.
```

Any idea of what it could be?

**Comment by lucasreis1** [comment]
Solved. I was missing double brackets.
