### ISSUE TITLE
Error running wpg (GLib.Error)

### ISSUE THREAD

**Issue by gatlinnewhouse** [deviantfero/wpgtk#27]
```bash
[delueze@rhizome ~]$ wpg
CURRENT WALL: /home/delueze/.wallpapers/background-edited.jpg
Traceback (most recent call last):
  File "/usr/bin/wpg", line 22, in <module>
    run()
  File "/usr/bin/wpgtk/wpg.py", line 210, in run
    win = mainWindow()
  File "/usr/bin/wpgtk/wpg.py", line 80, in __init__
    self.pixbuf_preview = GdkPixbuf.Pixbuf.new_from_file_at_scale( image_name, width=500, height=333, preserve_aspect_ratio=False )
GLib.Error: gdk-pixbuf-error-quark: Error interpreting JPEG image file (Improper call to JPEG library in state 200) (0)
```

Running Manjaro 64 bit.

**Comment by deviantfero** [comment]
It appears to be an invalid jpg, try replacing the image at that location
with the same name with another jpg, please post results.

**Comment by gatlinnewhouse** [comment]
You're right, I found the error. I think it corrupted my background image when I was running the `wpg -a image.jpg` and `wpg -s image.jpg` in the i3 config.

**Comment by gatlinnewhouse** [comment]
I'll add `bash ~/.wallpapers/wp_init.sh` to my i3 config

**Comment by deviantfero** [comment]
did it work for you?

**Comment by gatlinnewhouse** [comment]
Yep!
