### ISSUE TITLE
Python error on Ubuntu 22.10

### ISSUE THREAD

**Issue by vaskark** [deviantfero/wpgtk#272]
I'm recently seeing this:

```
Traceback (most recent call last):
  File "/usr/local/bin/wpg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/wpgtk/__main__.py", line 309, in main
    _gui.run(args)
  File "/usr/local/lib/python3.10/dist-packages/wpgtk/gui/theme_picker.py", line 196, in run
    win = mainWindow(args)
  File "/usr/local/lib/python3.10/dist-packages/wpgtk/gui/theme_picker.py", line 82, in __init__
    self.pixbuf_preview = GdkPixbuf.Pixbuf.new_from_file_at_scale(
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Error interpreting JPEG image file (Backing store not supported) (0)
```
Does anyone know what package I might be missing?
Thanks.

**Comment by vaskark** [comment]
Edit: I cleared out my `~/.config/wpg` folder and all is well. Not sure what the problem was. Might have been a corrupted wallpaper.
