### ISSUE TITLE
it not working :(((( 

### ISSUE THREAD

**Issue by OneDAZAI** [deviantfero/wpgtk#288]
Traceback (most recent call last):
  File "/home/guts/.local/bin/wpg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/guts/.local/pipx/venvs/wpgtk/lib/python3.11/site-packages/wpgtk/__main__.py", line 308, in main
    _gui = __import__("wpgtk.gui.theme_picker", fromlist=['theme_picker'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guts/.local/pipx/venvs/wpgtk/lib/python3.11/site-packages/wpgtk/gui/theme_picker.py", line 4, in <module>
    from . import color_grid
  File "/home/guts/.local/pipx/venvs/wpgtk/lib/python3.11/site-packages/wpgtk/gui/color_grid.py", line 12, in <module>
    from .color_picker import ColorDialog
  File "/home/guts/.local/pipx/venvs/wpgtk/lib/python3.11/site-packages/wpgtk/gui/color_picker.py", line 2, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'

**Comment by kleshas** [comment]
If this happened while importing pictures, then one of the pics was too simple for WPGTK to extract colours from.

**Comment by OneDAZAI** [comment]
i fix it thank for reply :))

**Comment by vaskark** [comment]
I'm having the exact same problem, same error message after trying to install with pipx. Just trying to open the program.

Any advice would be appreciated.
Thanks.

Ubuntu 23.10.1

**Comment by amplexus** [comment]
> I'm having the exact same problem, same error message after trying to install with pipx. Just trying to open the program.
> 
> Any advice would be appreciated. Thanks.
> 
> Ubuntu 23.10.1

I had same problem.

I had to (venv) pip3 install PyGObject  and it went away.
