### ISSUE TITLE
Pywal16 compatibility?

### ISSUE THREAD

**Issue by hownioni** [deviantfero/wpgtk#289]
[Continuing from this issue](https://github.com/deviantfero/wpgtk/issues/284)

I changed the lines of code inside /usr/lib/python3.11/site-packages/wpgtk/files.py and added the missing `True` argument. Now every time I run the command "Set" it prints this out:

`[i] theme_picker  current wallpaper: Cytus_1_Neko.png
[i] image         Using image Cytus_1_Neko.png.
[i] theme         Set theme to _home_wenus__config_wpg_wallpapers_Cytus_1_Neko_png_9_dark_wal__942796_1.1.0.json.
[i] colors        Found cached colorscheme.
[i] image         Using image Cytus_1_Neko.png.
[i] theme         Set theme to _home_wenus__config_wpg_wallpapers_Cytus_1_Neko_png_9_dark_wal__942796_1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[e] color         icons - base file does not exist
xrdb: No such file or directory
xrdb: can't open file '/home/wenus/.Xresources'
Error: Remote control is disabled
[w] reload        No settings daemon found, just refreshing Adwaita theme from gsettings
[i] wallpaper     Set the new wallpaper.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/wpgtk/gui/theme_picker.py", line 159, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.11/site-packages/wpgtk/data/themer.py", line 57, in set_theme
    Popen(settings['command'].split())
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1819, in _execute_child
    executable = args[0]
                 ~~~~^^^
IndexError: list index out of range`

I've been trying to fix it for a while but I don't know enough python to figure it out, at most I can assume it has to do with the package pywal16 which is pywal but creates a scheme of 16 instead of 9 and there's a new cols16 parameter to reflect this. If no compatibility is planned to be added, is there any way I can do it myself?

**Comment by hownioni** [comment]
The issue was unrelated to pywal16, it was just me trying to use the command toggle even though I wasn't passing any commands, I just disabled it and it started working again.
