### ISSUE TITLE
Template's not updating

### ISSUE THREAD

**Issue by KeepItDory** [deviantfero/wpgtk#292]
No matter what I can't seem to get my templates config file to update. I've done this before on my previous system but so far nothing works on my current. I started trying to make a template for tint2, and edit the colors with wpgtk colors, {color0] and so on. For example

`background_color = {color0} 100`

but the source file never updates when i run wpg. I even tried to replicate the example.txt as shown in your video but no luck with that either. Any idea what I'm doing wrong?

Edit: Starting WPGTK in terminal and running a WPG -s command gives the following messages

Traceback (most recent call last):
  File "/usr/bin/wpg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 305, in main
    process_args(args)
  File "/usr/lib/python3.11/site-packages/wpgtk/__main__.py", line 189, in process_args
    themer.set_theme(args.s[0], args.s[0], args.r)
  File "/usr/lib/python3.11/site-packages/wpgtk/data/themer.py", line 41, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/usr/lib/python3.11/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.11/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Color' object has no attribute 'red'

**Comment by KeepItDory** [comment]
Fixed by uninstalling python-pywal and wpgtk and installing pywal-git and wpgtk-git

Apologies.
