### ISSUE TITLE
Error adding wallpaper (similar to previous error)

### ISSUE THREAD

**Issue by vaskark** [deviantfero/wpgtk#310]
```
[i] theme_picker  current wallpaper: .current
Traceback (most recent call last):
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/gui/theme_picker.py", line 135, in on_add_clicked
    themer.create_theme(f)
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/themer.py", line 24, in create_theme
    return color.get_color_list(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/color.py", line 36, in get_color_list
    is_new = not os.path.isfile(files.get_cache_path(filename))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaskark/.local/lib/python3.12/site-packages/wpgtk/data/files.py", line 84, in get_cache_path
    return join(*filename)
           ^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not bool

```
I noticed that pywal16-git updated recently but I don't know if it's related.

**Comment by deviantfero** [comment]
it is related, the way the get_cache_path gets called is outdated for pywal16-git, I recommend using normal pywal in the meantime, I will fix this soon.

**Comment by deviantfero** [comment]
try the latest master, I won't upload to pypi until an issue in pywal16 is addressed, I'm thinking about dropping support for it and having my own pywal fork :thinking: can't keep bugging people bc something breaks with wpgtk

**Comment by vaskark** [comment]
Yup. Works fine again. As to the pywal issue I don't blame you.
Thanks again.
