### ISSUE TITLE
AttributeError: 'Color' object has no attribute 'red' error on Nixos

### ISSUE THREAD

**Issue by sandptel** [deviantfero/wpgtk#314]
**Command**

```bash wpg --theme $HOME/.cache/wal/colors.json -n```

I just wanted to match wpg to refresh colors when pywal colors are changed instead of doing other stuff.  Can anyone suggest alternative method to do this?

**Logs**
```
[i] theme         Set theme to colors.json.
[i] export        Exported json.
[i] image         Using image wallpapergreen.jpg.
[i] theme         Set theme to _home_roronoa__config_wpg_wallpapers_wallpapergreen_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
Traceback (most recent call last):
  File "/nix/store/9b45z9fihxw40q7awh3dykhji92k0c0i-wpgtk-6.5.9/bin/..wpg-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/9b45z9fihxw40q7awh3dykhji92k0c0i-wpgtk-6.5.9/lib/python3.12/site-packages/wpgtk/__main__.py", line 305, in main
    process_args(args)
  File "/nix/store/9b45z9fihxw40q7awh3dykhji92k0c0i-wpgtk-6.5.9/lib/python3.12/site-packages/wpgtk/__main__.py", line 290, in process_args
    themer.set_pywal_theme(args.theme, light)
  File "/nix/store/9b45z9fihxw40q7awh3dykhji92k0c0i-wpgtk-6.5.9/lib/python3.12/site-packages/wpgtk/data/themer.py", line 123, in set_pywal_theme
    set_theme(current, current)
  File "/nix/store/9b45z9fihxw40q7awh3dykhji92k0c0i-wpgtk-6.5.9/lib/python3.12/site-packages/wpgtk/data/themer.py", line 41, in set_theme
    pywal.export.every(colors, FORMAT_DIR)
  File "/nix/store/mx0gjllgngwl6h0nnn2bydqk4vfx81l0-python3.12-pywal-3.3.0/lib/python3.12/site-packages/pywal/export.py", line 68, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/nix/store/mx0gjllgngwl6h0nnn2bydqk4vfx81l0-python3.12-pywal-3.3.0/lib/python3.12/site-packages/pywal/export.py", line 15, in template
    template_data = "".join(template_data).format(**colors)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Color' object has no attribute 'red'
```
Also I saw this https://github.com/deviantfero/wpgtk/issues/292#issuecomment-1821942587 but not helpful for nix.

**Comment by deviantfero** [comment]
This is not a valid use-case for wpgtk. 

You're suposed to use wpgtk instead of pywal, wpgtk uses pywal's API to generate colorschemes from images and you can use it's UI to edit these themes.

wpg -a /path/to/wallpaper.jpg
wpg -s wallpaper.jpg -n

that's it, you're using pywal generated colorscheme without calling wal yourself.
