### ISSUE TITLE
Unable to set wallpaper or colorscheme with wpgtk

### ISSUE THREAD

**Issue by ExplosBlue** [deviantfero/wpgtk#85]
Selecting and setting an image does nothing, and no colorschemes are generated.

Commandline output: 
```INF::CURRENT WALL: .current
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/wpgtk/gui/theme_picker.py", line 179, in colorscheme_box_change
    self.sample.set_from_pixbuf(self.pixbuf_sample)
AttributeError: 'mainWindow' object has no attribute 'pixbuf_sample'
image: Using image /home/explos/.config/wpg/wallpapers/679478.jpg
wal: Generating a colorscheme...
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/wpgtk/gui/theme_picker.py", line 140, in on_set_clicked
    themer.set_theme(filename, colorscheme_file)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/themer.py", line 20, in set_theme
    color.apply_colorscheme(cs_file)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/color.py", line 176, in apply_colorscheme
    colors = prepare_colors(image_name)
  File "/usr/lib/python3.6/site-packages/wpgtk/data/color.py", line 158, in prepare_colors
    cdic = pywal.colors.get(image, config.WALL_DIR)
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 120, in get
    colors = gen_colors(img, color_count)
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 56, in gen_colors
    return [re.search("#.{6}", str(col)).group(0) for col in raw_colors[1:]]
  File "/usr/lib/python3.6/site-packages/pywal/colors.py", line 56, in <listcomp>
    return [re.search("#.{6}", str(col)).group(0) for col in raw_colors[1:]]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dylanaraps** [comment]
It looks like imagemagick is failing to run on your system. Some better error handling in wal for this would be nice. (I’ll add this)

Does running “convert img.png img.jpg” work on your system? (Use a real I put image)

**Comment by ExplosBlue** [comment]
Attempting to run the command `convert test.png test.jpg` was successful, no errors produced and the image converted sucessfully.

**Comment by deviantfero** [comment]
what about adding the image from the command line? `wpg -a ~/path/to/image.jpg`, does this produce a similar result, if so, you could also try and run pywal directly to set a wallpaper, this is just to confirm where the issue lies.

**Comment by ExplosBlue** [comment]
Running from commandline produces the same result as using the ui. Attempting to use pywal also appears to result in the same error being produced.

**Comment by deviantfero** [comment]
I think this is not `wpgtk`'s bug and I have no idea how you could solve it, could you provide info on your distro of choice, your wm or the like?
